/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Home/clean`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/hire` | `/Home/hire`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/profile` | `/Home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/works` | `/Home/works`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/clean`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/hire` | `/Home/hire`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/profile` | `/Home/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/works` | `/Home/works`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Home/clean${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/hire${`?${string}` | `#${string}` | ''}` | `/Home/hire${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/Home/profile${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/works${`?${string}` | `#${string}` | ''}` | `/Home/works${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Home/clean`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/hire` | `/Home/hire`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/profile` | `/Home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/works` | `/Home/works`; params?: Router.UnknownInputParams; };
    }
  }
}
