/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
<<<<<<< HEAD
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notification`; params?: Router.UnknownInputParams; } | { pathname: `/post-your-work`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/workdetails`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Home/clean`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/hire` | `/Home/hire`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/profile` | `/Home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/works` | `/Home/works`; params?: Router.UnknownInputParams; } | { pathname: `/screen/review`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/notification`; params?: Router.UnknownOutputParams; } | { pathname: `/post-your-work`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/workdetails`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/Home/clean`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/hire` | `/Home/hire`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/profile` | `/Home/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/Home${'/(tabs)'}/works` | `/Home/works`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/review`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/edit${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/notification${`?${string}` | `#${string}` | ''}` | `/post-your-work${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/workdetails${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/Home/clean${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/hire${`?${string}` | `#${string}` | ''}` | `/Home/hire${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/Home/profile${`?${string}` | `#${string}` | ''}` | `/Home${'/(tabs)'}/works${`?${string}` | `#${string}` | ''}` | `/Home/works${`?${string}` | `#${string}` | ''}` | `/screen/review${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/edit`; params?: Router.UnknownInputParams; } | { pathname: `/history`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/notification`; params?: Router.UnknownInputParams; } | { pathname: `/post-your-work`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/workdetails`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/Home/clean`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/hire` | `/Home/hire`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/profile` | `/Home/profile`; params?: Router.UnknownInputParams; } | { pathname: `/Home${'/(tabs)'}/works` | `/Home/works`; params?: Router.UnknownInputParams; } | { pathname: `/screen/review`; params?: Router.UnknownInputParams; };
=======
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/post-your-work`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hire` | `/hire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/works` | `/works`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/config/config`; params?: Router.UnknownInputParams; } | { pathname: `/screen/review`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/post-your-work`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/hire` | `/hire`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/works` | `/works`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/config/config`; params?: Router.UnknownOutputParams; } | { pathname: `/screen/review`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/post-your-work${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/hire${`?${string}` | `#${string}` | ''}` | `/hire${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/works${`?${string}` | `#${string}` | ''}` | `/works${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/config/config${`?${string}` | `#${string}` | ''}` | `/screen/review${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/post-your-work`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/hire` | `/hire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/works` | `/works`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/config/config`; params?: Router.UnknownInputParams; } | { pathname: `/screen/review`; params?: Router.UnknownInputParams; };
>>>>>>> 046037c269597856046027e78e1e20ece87f26ca
    }
  }
}
